name: Deploy to GitHub Pages

on:
  pull_request:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  PUBLIC_TTTM_WS_URL: wss://tttm.tttm.dev/sandbox
  PUBLIC_TTTM_URL: https:///tttm.tttm.dev

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 21
      #     cache: 'yarn'
      # - name: "Build it"
      #   run: yarn install --frozen-lockfile && yarn run build

      # Too slow. ;/
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv

      - run: nix profile install nixpkgs#devenv
      - run: devenv shell yarn run build

      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - uses: sarisia/actions-status-discord@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          username: tttm-site-bot
